services:
  db:
    container_name: postgres-cont
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'pgadmin'

    ports:
      - '8181:80'
    
    volumes:
      - vol-pgadmim-data:/var/lin/pgadmin

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmim-data:
    name: vol-pgadmim-data